spring.application.name=entertainment-lists

# ! ONLY FOR DEVELOPMENT
spring.datasource.url=jdbc:h2:mem:entertainment-lists

# ! ONLY FOR DEVELOPMENT
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ! ONLY FOR DEVELOPMENT
spring.datasource.username=admin
# ! ONLY FOR DEVELOPMENT
spring.datasource.password=admin

# ! ONLY FOR DEVELOPMENT
spring.jpa.show-sql=true

# ! ONLY FOR DEVELOPMENT
spring.h2.console.enabled=true

# Native support for .env files in Spring Boot
spring.config.import=optional:file:.env[.properties]

jwt.secret=${JWT_SECRET:vhM1KK7cHbaCKyGyBfNlH1qtcssPzFcbWksetfIT2IO}
cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}
